Prevent error due to podman bug when running tests
Sadly, I dont have an explanation for this one. I am able to reproduce the error
reliably, but only when running under tox:

```
Error: could not get runtime: error creating runtime static files directory
/root/.local/share/containers/storage/libpod: mkdir
/root/.local/share/containers: permission denied
```

This error does not happen when running the tests directly with pytest, only
when running under tox.

I am able to prevent this error from happening by explicitly telling podman to
use the current user's home directory. I would love to get to the bottom of this
one at some point.